# Generated by Django 3.1.14 on 2022-05-31 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcim', '0007_device_secrets_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceNotice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(editable=False)),
                ('duration', models.PositiveSmallIntegerField()),
                ('comments', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('devices', models.ManyToManyField(related_name='maintenance_notices', to='dcim.Device')),
            ],
            options={
                'verbose_name': 'Maintenance Notice',
                'verbose_name_plural': 'Maintenance Notices',
                'ordering': ('start_time', 'pk'),
            },
        ),
    ]
